# Setup
title:               OwnROM
tagline:             'A custom Android ROM made by the OwnDroid team'
description:         'This is Android our way, and the good way. This ROM is made by only friendly developers who are listening to the needs of their users.'
url:                 http://ownrom.github.io
baseurl:             ''
paginate:            5
paginate_path: "/blog/page:num/"


# About/contact
author:
  name:              Owndroid Team
  url:               https://ownrom.github.io
  email:             askowndroid@gmail.com

# Custom vars
version:             3.0 BETA

gems:
  - jekyll-asciidoc
  - jekyll-paginate
